const id = {
  rateLimited: 'Batas penggunaan telah tercapai. Silakan coba lagi nanti.',
  activePlan: 'Rencana belajar aktif', askStudyMate: 'Tanya StudyMate', planActions: 'Aksi rencana', clearPlan: 'Hapus rencana',
  overview: 'Ringkasan rencana', overviewTitle: 'Rencana Anda dalam satu tampilan', sessionFocus: 'Sesi belajar', viewOverview: 'Lihat ringkasan rencana', startLearning: 'Mulai belajar',
  overallProgress: 'Kemajuan keseluruhan', percentComplete: (value) => `${value}% selesai`, completed: 'Selesai', sessionsCount: (done, total) => `${done} / ${total} sesi`, mastery: 'Penguasaan', studyTime: 'Waktu belajar', hours: (value) => `~${value} jam`, schedule: 'Jadwal', progressAria: 'Kemajuan rencana belajar',
  learningSessions: 'Sesi belajar', preparingSessions: 'Menyiapkan sesi belajar…', sessionsUnavailable: 'Sesi belajar sementara tidak tersedia', planSafe: 'Dokumen rencana lengkap Anda tetap aman.', tryAgain: 'Coba lagi',
  latestAdjustment: 'Penyesuaian terbaru', planUpdate: 'Pembaruan rencana dari StudyMate', viewConversation: 'Lihat percakapan',
  curriculum: 'Kurikulum belajar', curriculumHint: 'Semua sesi dapat dibuka tanpa menunggu jadwal.', minutesPerSession: (value) => `${value} menit/sesi`,
  milestones: 'Pencapaian', sessionsComplete: (value) => `${value} sesi selesai`,
  assistantTitle: 'Perlu menyesuaikan rencana?', assistantDescription: 'Tanyakan sesi, kuis, materi, atau perubahan jadwal.',
  completePlan: 'Dokumen rencana lengkap', documentTitle: 'Rencana belajar lengkap', generatedFor: (level) => `Dibuat untuk level ${level}`, openDocument: 'Buka dokumen rencana lengkap',
  overviewIntro: 'Pahami keseluruhan rencana sebelum memulai sesi pertama.', selectedSession: 'Sesi yang akan dimulai',
  session: 'Sesi', minutes: (value) => `${value} menit`, activities: 'Aktivitas sesi',
  knowledgeCheck: 'Verifikasi pemahaman', quizTitle: 'Kuis sesi', answered: (value) => `${value}/5 dijawab`, quizDescription: 'Selesaikan lima soal untuk memverifikasi pemahaman sesi ini.', preparingQuiz: 'Menyiapkan kuis…', startQuiz: 'Mulai kuis', submitAnswers: 'Kirim jawaban',
  correct: 'Benar', reviewAnswer: 'Pelajari jawaban ini', latestScore: 'Nilai terbaru', bestScore: 'Nilai terbaik', masteryReached: 'Target penguasaan tercapai.', reviewRecommended: 'Sesi selesai, tetapi perlu dipelajari kembali.',
  continueSession: 'Lanjut ke sesi berikutnya', retryQuiz: 'Ulangi kuis', progressSummary: 'Lihat ringkasan kemajuan', references: 'Referensi belajar', quizLoadError: 'Kuis tidak dapat dimuat. Silakan coba lagi.', answerAll: 'Jawab seluruh lima soal sebelum mengirim.',
  assistantKicker: 'Asisten belajar', assistantEmptyTitle: 'Sesuaikan tanpa kehilangan target', assistantEmptyDescription: 'Tanyakan materi, kuis, tempo, atau hari belajar. Nyatakan dengan jelas jika ingin mengubah target utama.', you: 'Anda', responding: 'StudyMate sedang menjawab', requestFailed: 'Permintaan tidak dapat diselesaikan. Silakan coba lagi.', closeAssistant: 'Tutup asisten', adjustmentLabel: 'Sesuaikan rencana belajar', adjustmentPlaceholder: 'Tanyakan rencana, materi, atau kuis Anda…', adjustmentNote: 'Pertanyaan harus berkaitan dengan profil belajar. Nyatakan dengan jelas jika ingin mengubah target.', adjustmentRequired: 'Pesan tidak boleh kosong.', sendAdjustment: 'Kirim permintaan penyesuaian',
  clearTitle: 'Hapus rencana belajar ini?', clearDescription: 'Profil, rencana, percakapan, sesi, kuis, dan kemajuan akan dihapus permanen dari browser ini.', keepPlan: 'Pertahankan rencana', clearEverything: 'Hapus semuanya', cancelClear: 'Batalkan penghapusan rencana',
  levels: { beginner: 'pemula', intermediate: 'menengah', advanced: 'lanjutan' }, defaultMilestones: ['Bangun fondasi', 'Latih kemampuan inti', 'Review dan evaluasi'],
  statuses: { 'not-started': 'Belum dimulai', 'in-progress': 'Sedang berjalan', completed: 'Selesai', 'needs-review': 'Perlu dipelajari lagi' },
  days: { monday: 'Sen', tuesday: 'Sel', wednesday: 'Rab', thursday: 'Kam', friday: 'Jum', saturday: 'Sab', sunday: 'Min' },
}

const en = {
  rateLimited: 'The usage limit has been reached. Please try again later.',
  activePlan: 'Active study plan', askStudyMate: 'Ask StudyMate', planActions: 'Plan actions', clearPlan: 'Clear plan',
  overview: 'Plan overview', overviewTitle: 'Your plan at a glance', sessionFocus: 'Learning session', viewOverview: 'View plan overview', startLearning: 'Start learning',
  overallProgress: 'Overall progress', percentComplete: (value) => `${value}% complete`, completed: 'Completed', sessionsCount: (done, total) => `${done} / ${total} sessions`, mastery: 'Mastery', studyTime: 'Study time', hours: (value) => `~${value} hours`, schedule: 'Schedule', progressAria: 'Study plan progress',
  learningSessions: 'Learning sessions', preparingSessions: 'Preparing your sessions…', sessionsUnavailable: 'Sessions are temporarily unavailable', planSafe: 'Your complete study plan remains safe.', tryAgain: 'Try again',
  latestAdjustment: 'Latest adjustment', planUpdate: 'Plan update from StudyMate', viewConversation: 'View conversation',
  curriculum: 'Learning curriculum', curriculumHint: 'Every session can be opened without waiting for its scheduled day.', minutesPerSession: (value) => `${value} min/session`,
  milestones: 'Milestones', sessionsComplete: (value) => `${value} sessions complete`,
  assistantTitle: 'Need to adjust your plan?', assistantDescription: 'Ask about a session, quiz, material, or schedule change.',
  completePlan: 'Complete plan document', documentTitle: 'Complete study plan', generatedFor: (level) => `Generated for ${level}`, openDocument: 'Open complete plan document',
  overviewIntro: 'Understand the complete plan before starting your first session.', selectedSession: 'Session ready to start',
  session: 'Session', minutes: (value) => `${value} min`, activities: 'Session activities',
  knowledgeCheck: 'Knowledge check', quizTitle: 'Session quiz', answered: (value) => `${value}/5 answered`, quizDescription: 'Complete five questions to verify your understanding of this session.', preparingQuiz: 'Preparing quiz…', startQuiz: 'Start quiz', submitAnswers: 'Submit answers',
  correct: 'Correct', reviewAnswer: 'Review this answer', latestScore: 'Latest score', bestScore: 'Best score', masteryReached: 'Mastery target reached.', reviewRecommended: 'Session completed, but review is recommended.',
  continueSession: 'Continue to next session', retryQuiz: 'Retry same quiz', progressSummary: 'View progress summary', references: 'Learning references', quizLoadError: 'Quiz could not be loaded. Please try again.', answerAll: 'Answer all five questions before submitting.',
  assistantKicker: 'Learning assistant', assistantEmptyTitle: 'Adjust without losing your goal', assistantEmptyDescription: 'Ask about material, quizzes, pacing, or available days. Explicitly state if you want to change the main target.', you: 'You', responding: 'StudyMate is responding', requestFailed: 'We could not complete your request. Please try again.', closeAssistant: 'Close assistant', adjustmentLabel: 'Adjust your study plan', adjustmentPlaceholder: 'Ask about your plan, material, or quiz…', adjustmentNote: 'Questions should relate to your Study Profile. Explicitly state if you want to change the target.', adjustmentRequired: 'Message cannot be empty.', sendAdjustment: 'Send adjustment request',
  clearTitle: 'Clear this study plan?', clearDescription: 'Your profile, plan, conversation, sessions, quizzes, and progress will be permanently removed from this browser.', keepPlan: 'Keep plan', clearEverything: 'Clear everything', cancelClear: 'Cancel clearing the plan',
  levels: { beginner: 'beginner', intermediate: 'intermediate', advanced: 'advanced' }, defaultMilestones: ['Build the foundation', 'Practice core skills', 'Review and evaluate'],
  statuses: { 'not-started': 'Not started', 'in-progress': 'In progress', completed: 'Completed', 'needs-review': 'Needs review' },
  days: { monday: 'Mon', tuesday: 'Tue', wednesday: 'Wed', thursday: 'Thu', friday: 'Fri', saturday: 'Sat', sunday: 'Sun' },
}

export const getWorkspaceLabels = (language) => language === 'id' ? id : en
